#!/usr/bin/env bash
set -euo pipefail

# Phase 4: Create PR from sprint branch
# Usage: ./scripts/create-pr.sh <sprint-id> [--base <branch>] [--target <project-dir>]

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/config.sh"
source "${SCRIPT_DIR}/lib/github.sh"

sprint_id="$1"
shift || true

base_branch="main"
target_dir=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --base)   base_branch="$2"; shift 2 ;;
    --target) target_dir="$2"; shift 2 ;;
    *)        shift ;;
  esac
done

sprint_dir="${SPRINTS_DIR}/${sprint_id}"
target_dir="${target_dir:-$(pwd)}"
sprint_branch="sprint/${sprint_id}"

if [[ ! -d "$sprint_dir" ]]; then
  err "Sprint not found: ${sprint_id}"
  exit 1
fi

bold "Creating PR for Sprint: ${sprint_id}"
echo ""

# Ensure we're on the sprint branch
git -C "$target_dir" checkout "$sprint_branch" 2>/dev/null || {
  err "Sprint branch not found: ${sprint_branch}"
  exit 1
}

# Push sprint branch
info "Pushing sprint branch..."
git -C "$target_dir" push -u origin "$sprint_branch" 2>/dev/null || {
  err "Failed to push branch. Ensure remote is configured."
  exit 1
}

# Build PR body
pr_body="## Sprint: ${sprint_id}\n\n"

# Add task summary
if [[ -f "${sprint_dir}/plan.json" ]]; then
  pr_body+="### Tasks\n"
  pr_body+=$(python3 -c "
import json
with open('${sprint_dir}/plan.json') as f:
    plan = json.load(f)
for t in plan['tasks']:
    print(f\"- [x] **Task {t['id']}**: {t['title']} ({t['agent']}, {t.get('complexity', 'medium')})\")
")
  pr_body+="\n\n"
fi

# Add review summary
latest_review=$(ls -t "${sprint_dir}"/review-*.md 2>/dev/null | head -1)
if [[ -n "$latest_review" ]]; then
  pr_body+="### Review Summary\n"
  # Extract just the summary and verdict
  pr_body+=$(python3 -c "
import re
with open('${latest_review}') as f:
    content = f.read()

# Extract summary section
summary_match = re.search(r'## Summary\n(.*?)(?=\n##|\Z)', content, re.DOTALL)
if summary_match:
    print(summary_match.group(1).strip())

verdict_match = re.search(r'## Verdict\n(.*?)(?=\n##|\Z)', content, re.DOTALL)
if verdict_match:
    print(f'\n**Verdict:** {verdict_match.group(1).strip()}')
" 2>/dev/null || echo "Review completed")
  pr_body+="\n\n"
fi

# Add cost summary
if [[ -f "${sprint_dir}/cost.json" ]]; then
  pr_body+="### Agent Cost Summary\n"
  pr_body+=$(python3 -c "
import json
with open('${sprint_dir}/cost.json') as f:
    costs = json.load(f)
for agent, seconds in costs.get('by_agent', {}).items():
    print(f'- **{agent}**: {seconds}s')
" 2>/dev/null || echo "Cost data unavailable")
  pr_body+="\n\n"
fi

pr_body+="---\n\nGenerated by [dev-team](https://github.com/edhintz/dev-team) agentic sprint orchestrator"

# Show preview in supervised mode
if needs_approval "pr"; then
  echo ""
  info "PR Preview:"
  echo "---"
  echo -e "$pr_body"
  echo "---"
  echo ""
  confirm_or_exit "Create this PR?"
fi

# Get commit summary for title
commit_count=$(git -C "$target_dir" rev-list --count "${base_branch}..${sprint_branch}" 2>/dev/null || echo "?")
spec_name=$(basename "$(python3 -c "
import json
with open('${sprint_dir}/plan.json') as f:
    plan = json.load(f)
print(plan.get('spec', 'unknown'))
" 2>/dev/null || echo "sprint")" .md)

pr_title="[${sprint_id}] ${spec_name} (${commit_count} commits)"

# Create the PR
pr_url=$(gh pr create \
  --base "$base_branch" \
  --head "$sprint_branch" \
  --title "$pr_title" \
  --body "$(echo -e "$pr_body")" 2>&1) || {
  err "Failed to create PR"
  echo "$pr_url" >&2
  exit 1
}

ok "PR created: ${pr_url}"
echo "$pr_url" > "${sprint_dir}/.pr-url"

# Update sprint status
echo "pr-created" > "${sprint_dir}/.status"

# Close milestone if all issues are closed
if [[ -f "${sprint_dir}/.milestone" ]]; then
  milestone=$(cat "${sprint_dir}/.milestone")
  open_count=$(gh api "repos/:owner/:repo/milestones/${milestone}" --jq '.open_issues' 2>/dev/null || echo "?")
  if [[ "$open_count" == "0" ]]; then
    close_milestone "$milestone" 2>/dev/null && ok "Milestone closed" || true
  else
    info "${open_count} issues still open in milestone"
  fi
fi

echo ""
bold "Sprint ${sprint_id} PR is ready for human review!"
